name: breath_freely
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  currency_formatter: ^2.0.1
  draggable_bottom_sheet: ^1.0.2
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  liquid_pull_to_refresh: ^3.0.1
  photo_view: ^0.14.0
  dio: ^5.3.3
  retrofit: any
  shimmer: ^3.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  overlay_support: ^2.1.0
  flutter_animate: ^4.3.0
  syncfusion_flutter_datepicker: ^23.1.39
  change_app_package_name: ^1.1.0
  http_parser: ^4.0.2
  supabase_flutter: ^2.2.0
  tflite_flutter: ^0.10.4
  animated_text_kit: ^4.2.2
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0

  get: 4.6.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: any
  built_value_generator: any
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: any
  retrofit_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/tflite/
